from __future__ import annotations

import threading
from pathlib import Path

from database.connection import get_connection as get_postgres_connection

NEWS_MAPPING_DB_PATH = "postgresql:stock_app:news_mapping"

TABLE_STOCK_MASTER = "news_mapping_stock_master"
TABLE_STOCK_ALIAS = "news_mapping_stock_alias"
TABLE_CONCEPT_STOCK_MAP = "news_mapping_concept_stock_map"
TABLE_NEWS_ITEMS = "news_mapping_news_items"
TABLE_NEWS_STOCK_LINKS = "news_mapping_news_stock_links"
TABLE_MAPPING_FEEDBACK = "news_mapping_mapping_feedback"

_LOCK = threading.RLock()
_READY = False

_SCHEMA_DDL = [
    f"""CREATE TABLE IF NOT EXISTS {TABLE_STOCK_MASTER} (
        code TEXT PRIMARY KEY, ts_code TEXT, name TEXT, fullname TEXT,
        industry TEXT, area TEXT, list_date TEXT, aliases TEXT, updated_at TEXT
    )""",
    f"""CREATE TABLE IF NOT EXISTS {TABLE_STOCK_ALIAS} (
        alias TEXT NOT NULL, code TEXT NOT NULL, name TEXT, source TEXT,
        confidence DOUBLE PRECISION, updated_at TEXT, PRIMARY KEY (alias, code)
    )""",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_stock_alias_alias ON {TABLE_STOCK_ALIAS}(alias)",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_stock_alias_code ON {TABLE_STOCK_ALIAS}(code)",
    f"""CREATE TABLE IF NOT EXISTS {TABLE_CONCEPT_STOCK_MAP} (
        concept TEXT NOT NULL, code TEXT NOT NULL, name TEXT, relation_type TEXT,
        confidence DOUBLE PRECISION, evidence TEXT, source TEXT, updated_at TEXT,
        PRIMARY KEY (concept, code, relation_type)
    )""",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_concept_map_concept ON {TABLE_CONCEPT_STOCK_MAP}(concept)",
    f"""CREATE TABLE IF NOT EXISTS {TABLE_NEWS_ITEMS} (
        news_id TEXT PRIMARY KEY, date TEXT, publish_time TEXT, title TEXT,
        content TEXT, source TEXT, url TEXT, raw_text_hash TEXT, created_at TEXT
    )""",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_items_date ON {TABLE_NEWS_ITEMS}(date)",
    f"CREATE UNIQUE INDEX IF NOT EXISTS idx_news_mapping_items_hash ON {TABLE_NEWS_ITEMS}(raw_text_hash)",
    f"""CREATE TABLE IF NOT EXISTS {TABLE_NEWS_STOCK_LINKS} (
        news_id TEXT NOT NULL, code TEXT NOT NULL, name TEXT, link_type TEXT,
        confidence DOUBLE PRECISION, reason TEXT, evidence TEXT, mapper TEXT,
        status TEXT, created_at TEXT, PRIMARY KEY (news_id, code, mapper)
    )""",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_links_news ON {TABLE_NEWS_STOCK_LINKS}(news_id)",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_links_code ON {TABLE_NEWS_STOCK_LINKS}(code)",
    f"CREATE INDEX IF NOT EXISTS idx_news_mapping_links_status ON {TABLE_NEWS_STOCK_LINKS}(status)",
    f"""CREATE TABLE IF NOT EXISTS {TABLE_MAPPING_FEEDBACK} (
        feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        news_id TEXT, code TEXT, old_status TEXT, new_status TEXT,
        comment TEXT, created_at TEXT
    )""",
]


def get_connection(db_path: str | Path = NEWS_MAPPING_DB_PATH):
    _ = db_path
    return get_postgres_connection(runtime=False)


def execute_many(connection, query: str, rows) -> None:
    values = list(rows or [])
    if not values:
        return
    with connection.cursor() as cursor:
        cursor.executemany(query, values)


def init_db(db_path: str | Path = NEWS_MAPPING_DB_PATH) -> str:
    global _READY
    _ = db_path
    if _READY:
        return "stock_app"
    with _LOCK:
        if _READY:
            return "stock_app"
        with get_connection() as conn:
            conn.execute("SELECT pg_advisory_xact_lock(%s)", (836080807,))
            for statement in _SCHEMA_DDL:
                conn.execute(statement)
            conn.commit()
        _READY = True
    return "stock_app"


if __name__ == "__main__":
    init_db()
    print("news mapping PostgreSQL schema ready: stock_app")
