from __future__ import annotations

import threading

from database.connection import transaction

_LOCK = threading.RLock()
_READY = False

_RUNTIME_DDL = [
    """CREATE TABLE IF NOT EXISTS task_runs (
        task_id TEXT PRIMARY KEY, task_type TEXT NOT NULL, status TEXT NOT NULL,
        owner_id TEXT NOT NULL DEFAULT '', session_id TEXT NOT NULL DEFAULT '',
        request_json TEXT NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}',
        result_json TEXT, error_json TEXT, progress DOUBLE PRECISION NOT NULL DEFAULT 0,
        message TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, started_at TEXT,
        finished_at TEXT, updated_at TEXT NOT NULL, timeout_seconds BIGINT NOT NULL DEFAULT 99600,
        max_retries BIGINT NOT NULL DEFAULT 0, attempt BIGINT NOT NULL DEFAULT 0,
        cancel_requested BIGINT NOT NULL DEFAULT 0, worker_pid BIGINT, acknowledged_at TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_task_runs_lookup ON task_runs(owner_id, session_id, task_type, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_task_runs_status ON task_runs(status, updated_at DESC)",
    """CREATE TABLE IF NOT EXISTS task_events (
        sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id TEXT NOT NULL REFERENCES task_runs(task_id), event_type TEXT NOT NULL,
        data_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_task_events_task ON task_events(task_id, sequence)",
    """CREATE TABLE IF NOT EXISTS agent_run_checkpoints (
        run_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, user_id TEXT NOT NULL,
        status TEXT NOT NULL, checkpoint_json TEXT NOT NULL, version BIGINT NOT NULL,
        created_at TEXT NOT NULL, updated_at TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_agent_run_checkpoints_session_status ON agent_run_checkpoints(session_id, status)",
    """CREATE TABLE IF NOT EXISTS agent_request_checkpoints (
        run_id TEXT NOT NULL, request_id TEXT NOT NULL, status TEXT NOT NULL,
        checkpoint_json TEXT NOT NULL, updated_at TEXT NOT NULL,
        PRIMARY KEY(run_id, request_id)
    )""",
    """CREATE TABLE IF NOT EXISTS agent_session_state_items (
        memory_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, memory_key TEXT NOT NULL,
        value_json TEXT NOT NULL, value_type TEXT NOT NULL DEFAULT 'json', summary TEXT NOT NULL DEFAULT '',
        source_type TEXT NOT NULL DEFAULT '', source_ref TEXT NOT NULL DEFAULT '', confirmed BIGINT NOT NULL DEFAULT 0,
        confidence DOUBLE PRECISION NOT NULL DEFAULT 0.8, version BIGINT NOT NULL DEFAULT 1,
        status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
        expires_at TEXT NOT NULL, UNIQUE(session_id, memory_key, version)
    )""",
    "CREATE INDEX IF NOT EXISTS idx_agent_session_state_lookup ON agent_session_state_items(session_id, memory_key, status, version DESC)",
    "CREATE INDEX IF NOT EXISTS idx_agent_session_state_expiry ON agent_session_state_items(expires_at, status)",
    """CREATE TABLE IF NOT EXISTS agent_session_state_access_log (
        access_id TEXT PRIMARY KEY, session_id TEXT NOT NULL, run_id TEXT NOT NULL DEFAULT '',
        task_id TEXT NOT NULL DEFAULT '', agent_id TEXT NOT NULL DEFAULT '', operation TEXT NOT NULL,
        query_text TEXT NOT NULL DEFAULT '', matched_keys_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_agent_session_state_access_task ON agent_session_state_access_log(session_id, run_id, task_id, created_at)",
    """CREATE TABLE IF NOT EXISTS memory_records (
        memory_id TEXT PRIMARY KEY, user_id TEXT NOT NULL, conversation_id TEXT, run_id TEXT,
        task_id TEXT, source_type TEXT, source_id TEXT, memory_type TEXT NOT NULL,
        memory_subtype TEXT, scope TEXT, visibility TEXT, status TEXT, content TEXT, summary TEXT,
        topics_json TEXT, stock_codes_json TEXT, importance DOUBLE PRECISION, confidence DOUBLE PRECISION,
        created_at TEXT, updated_at TEXT, valid_from TEXT, valid_until TEXT, supersedes_memory_id TEXT,
        metadata_json TEXT, context_refs_json TEXT, message_refs_json TEXT, artifact_refs_json TEXT,
        approval_refs_json TEXT, source_refs_json TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_memory_records_user_type_status ON memory_records(user_id, memory_type, status, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_memory_records_source ON memory_records(source_type, source_id)",
]


def ensure_runtime_schema() -> None:
    global _READY
    if _READY:
        return
    with _LOCK:
        if _READY:
            return
        with transaction(runtime=True) as conn:
            # PostgreSQL Advisory Lock（顾问锁）跨进程序列化 Runtime Schema 初始化。
            # Python threading lock 只能保护单进程；API 与 docker exec/Worker
            # 可能在不同进程同时启动，因此 CREATE INDEX IF NOT EXISTS 仍可能
            # 在 PostgreSQL catalog（系统目录）层发生竞态。
            conn.execute(
                "SELECT pg_advisory_xact_lock(%s)",
                (836080806,),
            )
            for statement in _RUNTIME_DDL:
                conn.execute(statement)
        _READY = True
